apiVersion: v2
name: helm-chart
description: A generic chart for python web application
type: application
version: 0.1.0
# set dynamically on deployment, see: https://github.com/helm/helm/issues/8194
appVersion: "1.0.0"
